/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;
import static components.ItemAuthor.dbcon;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import tp1dpbo2022.FrameMain;
/**
 *
 * @author Iqbal Rynaldi
 */
public class ItemBuku extends javax.swing.JPanel{

    /**
     * Creates new form itemBuku
     */
    
    public FormUpdateBuku updateBuku;
    public String id,penerbit,author,desc,nameImg;
     private PopupMessage popup = new PopupMessage();

    public ItemBuku(String iId, String iPenerbit, String iAuthor, String iDesc, String iNameImg) throws SQLException {
        id = iId;
        penerbit = iPenerbit;
        author = iAuthor;
        desc = iDesc;
        nameImg = iNameImg;
        updateBuku = new FormUpdateBuku(id,penerbit,author,desc);
        initComponents();
        setLabel();
    }

    public void setLabel(){
        BufferedImage fileImg = null;
        try{
            fileImg = ImageIO.read(new File("src/assest/"+nameImg));
            Image dimg = fileImg.getScaledInstance(103, 103,Image.SCALE_SMOOTH);
            img.setIcon(new javax.swing.ImageIcon(dimg));
        }catch(IOException e){
             e.printStackTrace();
        }
        
        labelPenerbit.setText("Penerbit : " + penerbit);
        labelAuthor.setText("Author : " + author);
        
        labelDesc.setText("Desc :" + desc);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        labelPenerbit = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();
        labelDesc = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        img.setText("jLabel1");
        img.setToolTipText("");
        img.setVerifyInputWhenFocusTarget(false);
        img.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelPenerbit.setText("Penerbit : ");

        labelAuthor.setText("Author :");

        labelDesc.setText("Desc :");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(27, 27, 27)
                        .addComponent(btnDelete))
                    .addComponent(labelAuthor)
                    .addComponent(labelPenerbit)
                    .addComponent(labelDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPenerbit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDesc)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        JFrame update = new JFrame("Update Buku");
        update.add(updateBuku);
        update.pack();
        update.setVisible(true);
    }//GEN-LAST:event_btnUpdateMouseClicked
    final public void prosesDelete(){
        try {
            // TODO add your handling code here:
            dbcon.stm.execute("DELETE FROM `buku` WHERE `buku`.`id` = "+id+"");
            removeAll();
            revalidate();
            repaint();
            popup.textMessage.setText("Delete Berhasil");
            popup.tampil();
        } catch (SQLException ex) {
            Logger.getLogger(ItemAuthor.class.getName()).log(Level.SEVERE, null, ex);
            popup.textMessage.setText(ex.getMessage());
            popup.tampil();
        }
    }
    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        prosesDelete();
    }//GEN-LAST:event_btnDeleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel img;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JLabel labelPenerbit;
    // End of variables declaration//GEN-END:variables
}
