/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import tp1dpbo2022.FrameMain;
import tp1dpbo2022.dbConnection;

/**
 *
 * @author Iqbal Rynaldi
 */
public class ItemAuthor extends javax.swing.JPanel {

    /**
     * Creates new form itemAutor
     */
    
    static dbConnection dbcon = new dbConnection();
    public String id,name,jumlah,nameImg;
    public FormUpdateAuthor updateAuthor;
     private PopupMessage popup = new PopupMessage();

    public ItemAuthor(String iId, String iNameImg,String iName,String iJumlah) {
        id = iId;
        nameImg = iNameImg;
        name = iName;
        jumlah = iJumlah;
        updateAuthor = new FormUpdateAuthor(id,name,jumlah);
        initComponents();
        setLabel();
        
    }
    
    public String getID(){
        return id;
    }
    public void setLabel(){
        BufferedImage fileImg = null;
        try{
            fileImg = ImageIO.read(new File("src/assest/"+nameImg));
            Image dimg = fileImg.getScaledInstance(103, 103,Image.SCALE_SMOOTH);
            img.setIcon(new javax.swing.ImageIcon(dimg));
        }catch(IOException e){
             e.printStackTrace();
        }
        labelName.setText("Nama : " + name);
        labelJumlah.setText("Jumlah Buku : " + jumlah);
    }
    
    final public void prosesDelete(){
        try {
            // TODO add your handling code here:
            dbcon.stm.execute("DELETE FROM `author` WHERE `author`.`id` = "+id+"");
            removeAll();
            revalidate();
            repaint(); 
            popup.textMessage.setText("Delete Berhasil");
            popup.tampil();
        } catch (SQLException ex) {
            Logger.getLogger(ItemAuthor.class.getName()).log(Level.SEVERE, null, ex);
            popup.textMessage.setText(ex.getMessage());
            popup.tampil();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelJumlah = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("jLabel1");

        labelName.setText("Nama : ");

        labelJumlah.setText("Jumlah Buku : ");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(27, 27, 27)
                        .addComponent(btnDelete))
                    .addComponent(labelJumlah)
                    .addComponent(labelName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelName)
                        .addGap(18, 18, 18)
                        .addComponent(labelJumlah)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        prosesDelete();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        JFrame update = new JFrame("Update Author");
        update.add(updateAuthor);
        update.pack();
        update.setVisible(true);
    }//GEN-LAST:event_btnUpdateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    public static javax.swing.JButton btnUpdate;
    private javax.swing.JLabel img;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables

    private void addTab(String hahah, FormAuthor formAuthor) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
